
defaults: &defaults
  encoding: utf8
  username: kune
  password: db4kune

production:
  adapter: jdbcmysql
  database: kune_dev
  <<: *defaults

development:
  adapter: mysql
  database: kune_dev
  socket: /var/run/mysqld/mysqld.sock
  <<: *defaults

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

